version: '3.7'

services:
  neo4j:
    image: neo4j:4.1.3
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687

  main:
    build: ./relations-finder
    command: ["main.py", "${COMMAND:---help}"]
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test
      - NEO4J_URI=neo4j://neo4j:7687
    depends_on:
      - neo4j

  relations-viewer:
    build: ./relations-viewer
    stdin_open: true
    volumes:
      - ./relations-viewer/src:/app/src
    environment:
      - REACT_APP_NEO4J_USER=neo4j
      - REACT_APP_NEO4J_PASSWORD=test
      - REACT_APP_NEO4J_URI=bolt://localhost:7687
    ports:
      - 3000:3000
    depends_on:
      - neo4j
      - main
