version: '3.7'

services:
  neo4j:
    image: neo4j:4.1.3
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687

  main:
    build: .
    command: ["main.py", "${COMMAND:---help}"]
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test
      - NEO4J_URI=neo4j://neo4j:7687
    depends_on:
      - neo4j

  # ui:
  #   build: .
  #   command: [""]
  #   environment:
  #     - NEO4J_USERNAME=neo4j
  #     - NEO4J_PASSWORD=test
  #     - NEO4J_BOLT_URI=bolt://localhost:7687
  #     - UI_PORT=8000
  #     - UI_HOST=0.0.0.0
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - neo4j
  #     - main
