name: Continuous Integration

on: push

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - relations-finder
          - relations-viewer
    steps:
      - uses: actions/checkout@main
      - run: git fetch
      - name: lint
        run: make -C ${{ matrix.service }} lint
      - name: test
        run: make -C ${{ matrix.service }} test
  general-checks:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
